### ISSUE TITLE
[FALSE POSITIVE] Timer B

### ISSUE THREAD

**Issue by coolpvpv1** [DerRedstoner/CheatGuard#11]
## Main part
Server version (1.8/1.12/...): 1.8.8
Server core (Spigot/Paper/...): spigot
Video of false positive: obs glitched
How to recreate false positive: i was like running off a block then i held sneak to not fall off and sometimes you false Timer B idk why its weird

## Optional part
Link to config.yml file: default

**Comment by DerRedstoner** [comment]
Probably fixed.
