### ISSUE TITLE
Timer(A)

### ISSUE THREAD

**Issue by xProfik** [DerRedstoner/CheatGuard#2]
When I fly in creative mode, the plugin keeps saying: 9438583 failed Timer (A)
It happend 25 times in like 4 minutes. Could someone help me?
I turned Full bypass for players with OP. Still doesnt work, even after restarting server. (First i just reloaded plugin)
![image](https://user-images.githubusercontent.com/101166817/180947268-61264f31-01a7-4b67-8c40-6807ed8e5cd3.png)

**Comment by DerRedstoner** [comment]
All fixed
