### ISSUE TITLE
Add a method of punishment for Velocity

### ISSUE THREAD

**Issue by Regomy** [DerRedstoner/CheatGuard#4]
Sure, it looks weird, but I really liked the Velocity check in AAC3, maybe you could add it.

- Description of the check:
I'll attach the config here so you can see what's what: https://paste.md-5.net/uwabavatoh.bash
I don't know all the essence of this check, I don't have a code of this check too, so I will describe only the main principle. At impact, if player has modification of recoil, to it is added VL given in config, when VL reaches limit, player starts to teleport, for each teleport also +vl, if VL reaches maximum, set in Actions, with the player happens any action, kike, for example.
- Video: https://youtu.be/OZtdU861JFk)

**Comment by DerRedstoner** [comment]
suggestion rejected. may do in future but idk
