### ISSUE TITLE
[FALSE POSITIVE] Freecam

### ISSUE THREAD

**Issue by coolpvpv1** [DerRedstoner/CheatGuard#5]
## Main part
Server version (1.8/1.12/...): 1.8.8
Server core (Spigot/Paper/...): Spigot
Video of false positive: obs being stupid
How to recreate false positive: i was just on my localhost server with 0 ping running and jumping and falsing freecam a ton so its annoying to test 

## Optional part
Link to config.yml file: default

**Comment by coolpvpv1** [comment]
and of course i just looked the through the config and i cant disable it

**Comment by DerRedstoner** [comment]
Now disabled by default.
