### ISSUE TITLE
High Jump & AirJump check

### ISSUE THREAD

**Issue by Regomy** [DerRedstoner/CheatGuard#5]
=+= Information =+=
Version of protocollib: 4.8.0
Anti-cheat version: Latest version with SpigotMC
date of recording: Today
Client: liquidbounce b73
Module: HighJump
- mode: Vanilla
- Height:5.00
Proofs: https://youtu.be/XBQp7D31xlk

In the video, I included the speed module to show that I am not using any anti-cheat bypasses and it works and detects modules.

Noticed another problem, works AirJump if you walk up and stand close to the block, you can jump as much as you want without any problems, but there is a step back, then detects movement or fly. However, step Ncp in liquidbounce also works. Proofs: https://youtu.be/0BhSAG1R3lI

**Comment by DerRedstoner** [comment]
Added a high jump check. As for the airjump and step, I may patch those in the future (just don't expect tooo much from a free open-source anticheat)
