### ISSUE TITLE
The difference between cores

### ISSUE THREAD

**Issue by Regomy** [DerRedstoner/CheatGuard#6]
In the first video I used PaperSpigot 1.8.8, here the fly worked and allowed me to take off higher and less flagging, less often. The link is https://youtu.be/LSj35t22Kec (fly) https://youtu.be/noMBc6WzzEY (speed)

Second video:
Spigot 1.8.8, It's very hard to take off, flags during flight, I can't fly up. More frequent flags, times better detection. Link - https://youtu.be/gt2ZMf_ofac (fly) https://youtu.be/WzK75674-3U (speed)

The version of protocollib and core on the video, cheatguard version is the latest (1.1.4)

If it's not very clear, I'll reshoot the video.

**Comment by DerRedstoner** [comment]
I suggest you use the latest version of protocollib (4.8.0) and make sure there aren't any other plugins interfering with CheatGuard/ProtocolLib. Further I don't see why there should be a difference between paper and spigot.

Maybe downloading the newest 1.8.8 paper build as well?

**Comment by Regomy** [comment]
> I suggest you use the latest version of protocollib (4.8.0) and make sure there aren't any other plugins interfering with CheatGuard/ProtocolLib. Further I don't see why there should be a difference between paper and spigot.
> 
> Maybe downloading the newest 1.8.8 paper build as well?

I myself do not understand what it is, but I checked on the local host and of the plugins there only PermissionsEx, ProtocolLib, CheatGuard. Maybe if you check yourself, you can understand the reason or I am such a special?)

I recorded 2 more videos, with piper and spigot, there you can see the difference in flight detection speed. I used Protocollib 4.8.0 and the latest available version of PaperSpigot 1.8.8 downloaded from papermc.io

Here are the links:
- Video (PaperSpigot) : https://youtu.be/Ttenir9PQyc (Here the detection of fly was much longer, also VL were raised many times slower than on the 2 videos. )
- Viode (Spigot) : https://youtu.be/DULox2gyI9E
