### ISSUE TITLE
[FALSE POSITIVE] Jesus (A)

### ISSUE THREAD

**Issue by coolpvpv1** [DerRedstoner/CheatGuard#6]
## Main part
Server version (1.8/1.12/...): 1.8.8
Server core (Spigot/Paper/...): spigot
Video of false positive: obs wont record my screeen
How to recreate false positive: if you walk on the edge of a lilypad over water you will false jesus (A)

## Optional part
Link to config.yml file: default

**Comment by DerRedstoner** [comment]
Fixed in the next version!
