### ISSUE TITLE
[NEEDS FOR TOP ANTICHEAT] BUGS & ERRORS & SUGGESTIONS

### ISSUE THREAD

**Issue by F3F5** [DerRedstoner/CheatGuard#7]
1 - error: https://pastebin.com/ZE6pwUzU (maybe conflicts when protocol lib dev build, i dont know(maybe needs fix compatable for dev build)  on paper 1620 - 1.12.2
2 - killaura: killaura  check slow works/not all works on paper 1620 - 1.12.2
3 - add boatfly check & elytraflight
4 - add waterspeed check
5 - false flag when hit with optifine zoom.
6 - when you hit and spin often - killaura (F)
7 - 1.8 paper with protocollib 4.8.0 check very slow
8 - add 1.19.2 support
9 - update jar for spigot, not only github
10 - full false flags in 1.16.5,

![Screenshot_1](https://user-images.githubusercontent.com/108226177/189557097-cefbc48f-2abf-4cc4-b52a-d68752b96e6a.png)

**Comment by DerRedstoner** [comment]
Thanks for the suggestions. I'll try to fix most of these when I get the time.
