### ISSUE TITLE
[FALSE POSITIVE] Speed H

### ISSUE THREAD

**Issue by coolpvpv1** [DerRedstoner/CheatGuard#8]
Main part
Server version (1.8/1.12/...): 1.8.8
Server core (Spigot/Paper/...): Spigot
Video of false positive: sorry obs is glitched 
How to recreate false positive: if you jump down slabs like this you will false Speed H https://imgur.com/iGfISB2

Optional part
Link to config.yml file: Its Default

**Comment by DerRedstoner** [comment]
Fixed!
