### ISSUE TITLE
[FALSE POSITIVE] Speed H

### ISSUE THREAD

**Issue by coolpvpv1** [DerRedstoner/CheatGuard#9]
## Main part
Server version (1.8/1.12/...): 1.8.8
Server core (Spigot/Paper/...): spigot
Video of false positive: obs glitched
How to recreate false positive: if you sprint and jump on lilypads down a line kinda like this https://imgur.com/HZ6wv2d

## Optional part
Link to config.yml file: default

**Comment by DerRedstoner** [comment]
Fixed!
